---
- name: create a docker ansible or other ssh based environment
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - lab_vars.yml  

  tasks:

  - name: create lab network {{ docker_network }} with options
    docker_network:
      name: "{{ docker_network }}"
      driver_options:
        com.docker.network.bridge.name: "{{ docker_bridge_name }}"
      ipam_options:
        subnet: "{{ docker_subnet }}"
        gateway: "{{ docker_gateway }}"
    tags:
      - create_lab_network

  - name: create lab hosts 
    docker_container:
      name: "{{ item.name }}"
      image: "{{ docker_image }}"
      ports:
        "{{ item.port_maps }}"
      networks:
        - name: "{{ docker_network }}"
          ipv4_address: "{{ item.ip }}"
      env:
        SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
        SSH_USER: vagrant
    with_items: "{{ lab_machines }}"

  - name: create in-memory inventory
    add_host:
      name: "{{ item.name }}"
      groups: "{{ item.group}}"
    with_items: "{{ lab_machines }}"
    tags:
      - create_in-memory_inventory

  - name: create lab directory
    file:
      path: "{{ lab_directory }}"
      state: directory
      mode: 0755

  - name: write static inventory file
    template:
      src: templates/lab_inventory.j2
      dest: "{{ lab_directory }}/hosts"
    tags:
      - write_static_inventory

  - name: write ansible lab config files
    template:
      src: "templates/{{ item }}.j2"
      dest: "{{ lab_directory }}/{{ item }}"
    with_items:  
      - ansible.cfg
      - ssh.cfg  
      - ssh-jumpbox.cfg  
    tags:
      - file_gen    

- name: smoke test lab
  hosts: all
  gather_facts: false

  tasks:
    
  - name: ping lab hosts
    ping:

