---
- name: Create in-memory inventory
  add_host:
    name:                 "{{ item.value.name }}"
    groups:               "{{ item.value.group }}"
    ansible_ssh_host:     "{{ item.value.ip }}"
  with_dict:              "{{ lab_machines }}"
...
